spring.application.name=final_exam_work

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.jpa.hibernate.ddl-auto=validate

spring.profiles.active=local

file.upload-dir=uploads



