spring.application.name=final_exam_work

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
logging.level.org.hibernate.type.descriptor.sql=DEBUG

spring.jpa.hibernate.ddl-auto=validate


spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.profiles.active=local

file.upload-dir=uploads



