INSERT INTO roles(role) VALUES ('CONTRIBUTOR') ON CONFLICT DO NOTHING;
INSERT INTO roles(role) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles(role) VALUES ('MEMBER') ON CONFLICT DO NOTHING;